#!/usr/bin/env bash
# Installing Nginx and configuring it with X-Served-By header

# Update package manager
sudo apt update -y

# Install Nginx
sudo apt install nginx -y

# Backup default Nginx config
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Create new configuration with custom header
new_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.html index.nginx-debian.html;

    server_name _;

    add_header X-Served-By $(hostname);
}
"

# Write new config as root
echo "$new_config" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo systemctl restart nginx
